// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9UwXA2FMki5OqZw_Xhu4A-jyBSYU6vqg',
    appId: '1:991837907165:web:b73834580c7acbec699334',
    messagingSenderId: '991837907165',
    projectId: 'my-digital-writting-book',
    authDomain: 'my-digital-writting-book.firebaseapp.com',
    storageBucket: 'my-digital-writting-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWHtdChdCgRgqcjtUfnT2ZwrxgPCw2f9k',
    appId: '1:991837907165:android:ec493c9a5fde1b1a699334',
    messagingSenderId: '991837907165',
    projectId: 'my-digital-writting-book',
    storageBucket: 'my-digital-writting-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUM-RLZZJbryDe30yIF8MmZu_hLx61ZH4',
    appId: '1:991837907165:ios:328dd36be0c50984699334',
    messagingSenderId: '991837907165',
    projectId: 'my-digital-writting-book',
    storageBucket: 'my-digital-writting-book.appspot.com',
    androidClientId: '991837907165-18lkgpiclj6efer812d860utg9iek11l.apps.googleusercontent.com',
    iosClientId: '991837907165-k6qc7501l8b803nc5fp1c92p3jodsros.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUM-RLZZJbryDe30yIF8MmZu_hLx61ZH4',
    appId: '1:991837907165:ios:fff5cceace1b81cb699334',
    messagingSenderId: '991837907165',
    projectId: 'my-digital-writting-book',
    storageBucket: 'my-digital-writting-book.appspot.com',
    androidClientId: '991837907165-18lkgpiclj6efer812d860utg9iek11l.apps.googleusercontent.com',
    iosClientId: '991837907165-dfn99ujso5n1kkjuh0c94kbc4aqgogog.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp.RunnerTests',
  );
}
